### ISSUE TITLE
Difference in numbers from condastats and anaconda.org

### ISSUE THREAD

**Issue by nicrie** [conda-incubator/condastats#18]
* condastats version: 0.2.1
* Python version: 3.11.4
* Operating System: Ubuntu 22.04

### Description

Getting the total/monthly download number from `condastats` for a package (`xeofs`) differs from the number you find on the corresponding [anaconda website](https://anaconda.org/conda-forge/xeofs)

### What I Did

``` sh
condastats overall xeofs
```
The above command results in 1191, whereas the  [anaconda website](https://anaconda.org/conda-forge/xeofs) states 4091. Where does the difference come from?

btw: Thanks for this super cool tool! :)

**Comment by sophiamyang** [comment]
Sorry for the late reply. @seibert could you help with this question? Thanks!

**Comment by phwuil** [comment]
Hi @nicrie and @sophiamyang , it is quite frustrating to see that @nicrie and I have quite the same configuration, and he can get stats from condastats and I cannot :-) (see https://github.com/sophiamyang/condastats/issues/17) ... Can we try to find the difference between our configurations ?

- condastats==0.2.1
- pandas==2.1.1
- pyarrow==13.0.0
- dask==2023.9.3

- python 3.11.5
- linux (manjaro 23.0)

(what else ?)

**Comment by jakirkham** [comment]
@jezdez would it make sense to transfer this to https://github.com/ContinuumIO/anaconda-package-data ?

**Comment by jakirkham** [comment]
@jezdez think running [this `gh` command]( https://cli.github.com/manual/gh_issue_transfer ) should work

```
gh issue transfer https://github.com/conda-incubator/condastats/issues/18 https://github.com/ContinuumIO/anaconda-package-data
```

Unfortunately lack the permissions to complete it

**Comment by jezdez** [comment]
@jakirkham IIUC we can't move this ticket to the other repo, since it's not stored in the same organization sadly

**Comment by jakirkham** [comment]
Thanks Jannis! 🙏

Yes @nicrie could you please raise [a new issue on `ContinuumIO/anaconda-package-data`]( https://github.com/ContinuumIO/anaconda-package-data/issues/new )? Once open please link it here and close this one out

**Comment by nicrie** [comment]
Thanks, @jakirkham! I hadn't seen that thread before. It looks like the underlying issue (linked in the thread you shared) is discussed here:

https://github.com/ContinuumIO/anaconda-package-data/issues/45#issuecomment-2147788870

They made a change in June 2024, and now the download stats seem more accurate for me. I'll keep an eye on that discussion. Thanks for pointing me in the right direction and for your patience!

**Comment by phwuil** [comment]
Hello, any news about this issue ?

**Comment by cappadona** [comment]
> Edit: Admittedly there is some overlap with issue ( https://github.com/ContinuumIO/anaconda-package-data/issues/52 ). So it may make sense to consolidate there. Please read it over and comment over there if you agree

@jakirkham Thanks for connecting the dots here 🙏🏼 


* @phwuil I just commented on https://github.com/ContinuumIO/anaconda-package-data/issues/52#issuecomment-2334649224 and hopefully we can continue the conversation there
